In [1]:
import djlib as dj
import plotly.graph_objects as go
import numpy as np
from scipy.interpolate import griddata


In [2]:
data = dj.vasputils.casm_query_reader('ground_states.json')
data.keys()

dict_keys(['comp', 'energy', 'formation_energy', 'name', 'selected'])

In [3]:
comp = np.array(data['comp'])
print(comp.shape)
formation_energy = np.reshape(np.array(data['formation_energy']),(-1,1))
print(formation_energy.shape)
points = np.hstack((comp, formation_energy))
print(points)


(8, 2)
(8, 1)
[[ 0.5         0.5        -0.2209975 ]
 [ 0.75        0.25       -0.12840725]
 [ 0.33333333  0.66666667 -0.194528  ]
 [ 0.66666667  0.33333333 -0.16843767]
 [ 0.16666667  0.83333333 -0.10698983]
 [ 0.5         0.16666667 -0.5114225 ]
 [ 0.16666667  0.5        -0.5838975 ]
 [ 0.33333333  0.33333333 -0.56196967]]


In [4]:
x = np.linspace(0,1)
x,y = np.array(np.meshgrid(x,x))
grid = np.array([[x[i,j], y[i,j]] for i in range(len(x)) for j in range(len(x))])
print(grid.shape)


(2500, 2)


In [5]:
z = griddata(points=comp, values=formation_energy, xi = grid, method='linear')
z = z.reshape(50,50)
print(z.shape)
print(grid.shape)

(50, 50)
(2500, 2)


In [6]:
fig = go.Figure(data=[go.Surface(z=z, x = np.linspace(0,1), y=np.linspace(0,1))])
fig.show()